language: php

php:
  # - 5.4
  # - 5.5
  # - 5.6
  - 7.0
#  - hhvm

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer update --dev --prefer-dist --no-interaction

before_script:
  - ./init --env=Development --overwrite=All
  - touch common/config/config.yml
  - mysql -e 'CREATE DATABASE yii2advanced_test;'
  - php yii_test migrate --interactive=0
  - phantomjs --webdriver=4444 &
  - php -S 127.0.0.1:8080 -t 'frontend/web' > /dev/null 2>&1 &
  - sleep 5

script:
  - composer validate --strict
  - vendor/bin/codecept run
